# Deploys AlertsProduction Dev GKE with Terraform
name: 'Alerts Dev GKE'

on:
  pull_request:
    paths:
      - 'environment/deployments/alert-prod/env/dev-gke.tfvars'
  push:
    paths:
      - 'environment/deployments/alert-prod/env/dev-gke.tfvars'
    branches:
      - main
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/alert-prod/gke
      state_prefix: alert-prod/dev/gke
      tfvars_file: ../env/dev-gke.tfvars
    secrets: inherit
