# Deploys Butler Integration VPC Peering with Terraform
name: 'Butler DEV VPC Peering to PanDa'

on:
  pull_request:
    paths:
      - 'environment/deployments/butler-repo/env/dev-vpcpeer2.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/deployments/butler-repo/env/dev-vpcpeer2.tfvars'
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/butler-repo/vpc_peering
      state_prefix: butler-repo/dev/vpc_peer2
      tfvars_file: ../env/dev-vpcpeer2.tfvars
    secrets: inherit
