# Deploys Dev Integration GCP Project with Terraform
name: 'Data Curation PROD GCP Project'

on:
  pull_request:
    paths:
      - 'environment/deployments/data-curation/env/production.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/deployments/data-curation/env/production.tfvars'
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/data-curation
      state_prefix: data-curation/prod
      tfvars_file: env/production.tfvars
    secrets: inherit
