# Deploys QServ Integration GKE with Terraform
name: 'PanDA DEV GKE'

on:
  pull_request:
    paths:
      - 'environment/deployments/panda/env/dev-gke.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/deployments/panda/env/dev-gke.tfvars'
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/panda/gke
      state_prefix: panda/dev/gke
      tfvars_file: ../env/dev-gke.tfvars
    secrets: inherit
