# Deploys PPDB Int Services with Terraform
name: 'PPDB Int Services'

on:
  pull_request:
    paths:
      - 'environment/deployments/ppdb/env/int-services.tfvars'
  push:
    paths:
      - 'environment/deployments/ppdb/env/int-services.tfvars'
    branches:
      - main
  # Re-enable this when/if we want to deal with drift
  schedule:
    - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/ppdb/services
      state_prefix: ppdb/int/services
      tfvars_file: ../env/int-services.tfvars
    secrets:
      gcp_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      terraform_state_bucket: ${{ secrets.TERRAFORM_STATE_BUCKET }}
      slack_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
