# Deploys PPDB Dev Cloud SQL with Terraform
name: 'PPDB Dev Cloud SQL'

on:
  pull_request:
    paths:
      - 'environment/deployments/ppdb/env/dev-cloudsql.tfvars'
  push:
    paths:
      - 'environment/deployments/ppdb/env/dev-cloudsql.tfvars'
    branches:
      - main
      # Re-enable this when/if we want to deal with drift
      # schedule:
      # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/ppdb/cloudsql
      state_prefix: ppdb/dev/cloudsql
      tfvars_file: ../env/dev-cloudsql.tfvars
    secrets:
      gcp_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      terraform_state_bucket: ${{ secrets.TERRAFORM_STATE_BUCKET }}
      slack_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
