# Deploys PPDB GCP Int Project with Terraform
name: 'PPDB Int GCP Project'

on:
  pull_request:
    paths:
      - 'environment/deployments/ppdb/env/int.tfvars'
  push:
    paths:
      - 'environment/deployments/ppdb/env/int.tfvars'
    branches:
      - main
      # Re-enable this when/if we want to deal with drift
      # schedule:
      # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/ppdb
      state_prefix: ppdb/int
      tfvars_file: env/int.tfvars
    secrets: inherit
