# Deploys roundtable-dev GCP Project with Terraform
name: 'Roundtable Dev Cloud SQL'

on:
  pull_request:
    paths:
      - 'environment/deployments/roundtable/env/dev-cloudsql.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/deployments/roundtable/env/dev-cloudsql.tfvars'
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/roundtable/cloudsql
      state_prefix: roundtable/dev/cloudsql
      tfvars_file: ../env/dev-cloudsql.tfvars
    secrets: inherit
