# Deploys Roundtable Dev GCP Project with Terraform
name: 'Roundtable Dev GCP Project'

on:
  pull_request:
    paths:
      - 'environment/deployments/roundtable/env/dev.tfvars'
  push:
    paths:
      - 'environment/deployments/roundtable/env/dev.tfvars'
    branches:
      - main
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/roundtable
      state_prefix: roundtable/dev
      tfvars_file: env/dev.tfvars
    secrets: inherit
