# Deploys Science Platform Integration GCP Project with Terraform
name: 'RSP INT GCP Project'

on:
  pull_request:
    paths:
      - 'environment/deployments/science-platform/env/integration.tfvars'
  push:
    paths:
      - 'environment/deployments/science-platform/env/integration.tfvars'
    branches:
      - main
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/science-platform
      state_prefix: science-platform/int
      tfvars_file: env/integration.tfvars
      gcp_credentials_secret: PIPELINE_RSP_INT_PROJECT
    secrets: inherit
