# Deploys New Science Platform Stable GCP Project with Terraform
name: 'RSP STABLE NEW GKE'

on:
  pull_request:
    paths:
      - 'environment/deployments/science-platform/env/production-new-gke.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/deployments/science-platform/env/production-new-gke.tfvars'
  schedule:
    - cron: 25 2 * * *
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/science-platform/gke
      state_prefix: science-platform/stable/new-gke
      tfvars_file: ../env/production-new-gke.tfvars
      apply_on_workflow_dispatch: true
    secrets: inherit
