# Deploys Science Platform Stable GCP Project with Terraform
name: 'RSP STABLE ALERTDB'

on:
  pull_request:
    paths:
      - 'environment/deployments/science-platform/env/production-alertdb.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/deployments/science-platform/env/production-alertdb.tfvars'
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/science-platform/alertdb
      state_prefix: science-platform/stable/alertdb
      tfvars_file: ../env/production-alertdb.tfvars
    secrets: inherit
