# Deploys Science Platform Demo GCP Project with Terraform
name: 'RSP Demo GCP Project'

on:
  # workflow_dispatch # Comment out below, uncomment this to disable
  # For the "proj" workflows only: This running depends on cloudsql
  # running first, so leave this one commented out until clouldsql
  # has been revived.
  pull_request:
    paths:
      - 'environment/deployments/science-platform/env/demo.tfvars'
  push:
    paths:
      - 'environment/deployments/science-platform/env/demo.tfvars'
    branches:
      - main
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/science-platform
      state_prefix: science-platform/demo
      tfvars_file: env/demo.tfvars
    secrets: inherit
