# Deploys Science Platform Demo GCP Project with Terraform
name: 'RSP DEMO ALERTDB'

on:
  workflow_dispatch
  # pull_request:
  #   paths:
  #     - 'environment/deployments/science-platform/env/demo-alertdb.tfvars'
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'environment/deployments/science-platform/env/demo-alertdb.tfvars'
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/science-platform/alertdb
      state_prefix: science-platform/demo/alertdb
      tfvars_file: ../env/demo-alertdb.tfvars
    secrets: inherit
