# Deploys Science Platform Integration GCP Project with Terraform
name: 'RSP DEMO FIRESTORE GCP Project'

on:
  workflow_dispatch # Comment out below, uncomment this to disable
  # pull_request:
  #   paths:
  #     - 'environment/deployments/science-platform/firestore/env/demo.tfvars'
  # push:
  #   paths:
  #     - 'environment/deployments/science-platform/firestore/env/demo.tfvars'
  #   branches:
  #     - main
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/deployments/science-platform/firestore
      state_prefix: science-platform/firestore/demo
      tfvars_file: env/demo.tfvars
    secrets: inherit
