# Deploys Folders in GCP with Terraform
name: 'GCP Folders'

on:
  pull_request:
    paths:
      - 'environment/foundation/1-org-b/1-org-b.tfvars'
  push:
    paths:
      - 'environment/foundation/1-org-b/1-org-b.tfvars'
    branches:
      - main
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/foundation/1-org-b/
      state_prefix: foundation/1-org-b
      tfvars_file: 1-org-b.tfvars
    secrets: inherit
