# Deploys GCP Network Foundation
name: 'GCP Network Foundation'

on:
  pull_request:
    paths:
      - 'environment/foundation/2-networks/network.tfvars'
  push:
    branches:
      - main
    paths:
      - 'environment/foundation/2-networks/network.tfvars'
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/foundation/2-networks/
      state_prefix: foundation/2-networks
      tfvars_file: network.tfvars
    secrets: inherit
