# Deploys GCP Google Groups Foundation
name: 'GCP Google Groups'

on:
  pull_request:
    paths:
      - 'environment/foundation/google_groups/env/groups.tfvars'
  push:
    paths:
      - 'environment/foundation/google_groups/env/groups.tfvars'
    branches:
      - main
  # Re-enable this when/if we want to deal with drift
  # schedule:
  # - cron: 25 2 * * *

jobs:
  terraform:
    name: Terraform
    uses: ./.github/workflows/_reusable-terraform-plan-apply.yaml
    with:
      working_directory: ./environment/foundation/google_groups/
      state_prefix: foundation/google_groups
      tfvars_file: env/groups.tfvars
    secrets: inherit
